### PR TITLE
Build the snap in travis

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
Hello again! I'm sorry for the noise. I think the travis yaml is a little crazy, but in the end I could make it work :)
Building it is the first step to continuously deliver the snap to the store. But to actually publish it you will need to register the name: https://myapps.developer.ubuntu.com/dev/click-apps/register-name/

Are you still interested in publishing it?

**Comment by elopio** [comment]
@woodyrew @Ajedi32 I'm coming back from holidays and catching up with some pending discussions from last year. I would love to work with you to get metalsmith released to the store and with continuous delivery from travis. Please let me know when you have some time.

**Comment by Ajedi32** [comment]
Thanks, you instructions on #249 were pretty clear. I'll give it a shot. After reading over the page at http://snapcraft.io/docs/build-snaps/publish though I do have a couple questions:

1. If I register `metalsmith` under my account, will I be the only one allowed to publish updates to it? Ideally, everyone in the [`metalsmith`](https://github.com/metalsmith) org should be allowed to push out new versions, not just me.
2. I didn't see any mention of a versioning system beyond the separate stable, candidate, beta, and edge release channels. What happens if we need to push a major, breaking change to the store? How will users be able to specify which version of Metalsmith they want?

**Comment by elopio** [comment]
Hello @Ajedi32,

The Ubuntu store has a collaboration feature. So you can invite maintainers by mail, and they then can push new revisions of your snap. All of that is done on the store website. However, I would suggest to register the snap with a shared email address and developer name, so when people install it, it comes from the metalsmith account, not from your personal one. Then you can sent a contribution invite to your personal email.

About major versions, we are working on more features to be able to do something like stable/2.0, edge/3.x. For now, what people are doing is to name the snap with the major version, like postgresql9. Same as it's currently done in the deb archives.

**Comment by Ajedi32** [comment]
Okay, I guess I'll just create an account for the Metalsmith Org then and publish under that name. The current revision will probably get published as "metalsmith2" or something like that.

**Comment by elopio** [comment]
I'm closing this, because it's no longer necessary to do the push to the store from travis.
Now we have https://build.snapcraft.io, that will take care of building and pushing every change in master, with a couple of clicks. Give it a try! :)

**Pull request closed without merging**
