### PR TITLE
Add `file` key to the files hash

### PR DESCRIPTION
**Pull request by gjtorikian**
For a plugin I'm working on, it would be great to have access to the original filename on the files that come back. We only get the `stat` object, which can't trace back the original filename.

### CODE REVIEW

**Comment by Ajedi32** [comment]
There was some discussion about this already in #58. The problem with including a `file` key like this is it's misleading. Updating that value in a plugin won't change the location of the file, and updating the key pointing to the file in the files object won't update this key.

It seems your intention is a bit different here though. Maybe a name like `source_file` would better reflect what you intend this key to be used for?

**Comment by Ajedi32** [comment]
Also, just curious: why do you want to know the original file path anyway? Metalsmith is supposed to abstract that detail away entirely.

**Comment by woodyrew** [comment]
I usually have an identifier like a slug for that sort of thing.
You could create a plugin that adds the `filename` as metadata?

**Comment by woodyrew** [comment]
Here's a couple of plugin examples that might help out.
```js
/**
 * Adds source filename to file like front matter
 */
var original_filename = function (files, metalsmith, done) {
    Object.keys(files).forEach(function (file) {
        files[file].original_filename = file;
    });
    done();
};
```
or if you wanted to track the changes, this would initialise a metadata object with the source filenames.

```js
/**
 * Adds filename tracking object to metadata
 */
var filename_tracking = function (files, metalsmith, done) {
    var metadata = metalsmith.metadata();
    var file_list = [];
    Object.keys(files).forEach(function (file) {
        
        file_list.push({source_file: file});
    });

    metadata.filetracking = file_list;

    done();
};
```

**Comment by gjtorikian** [comment]
Thanks @woodyrew, those examples helped a ton. I can work around this.

**Pull request closed without merging**
