### PR TITLE
Default callback for Metalsmith.build()

### PR DESCRIPTION
**Pull request by eimajenthat**
Someone smarter than me might be able to come up with a more elegant solution than mine, I've give what I have.  The build function only works if you pass it a callback, which is somewhat unintuitive.  This change accepts your callback, but if you don't provide one, it inserts a default callback which simply throws any errors returned.

Generators are a new thing for me, and I feel like my changes are tacky and ugly, defacing some very elegant code.  However, in my tests, they do seem to work, which is more important than elegance.  If anyone has a way to improve this and provide the same functionality with more elegance, I'll be your biggest fan.

### CODE REVIEW

**Comment by doup** [comment]
:+1: on this. It's really weird that in the project webpage everywhere `build()` is used without providing a callback. At least on GitHub the examples use a callback.

Few days ago a friend tried Metalsmith… but he switched for Jekyll as the builds where not working. I suspect that it has something to do with this… :-)

**Comment by ianstormtaylor** [comment]
I think this breaks the generator use?

**Comment by dominicbarnes** [comment]
Yeah, I believe it does, so I think we should pass on this PR. If anything, this is probably an issue that `unyield` should solve.

**Comment by eimajenthat** [comment]
I wish I knew how to apply unyield to this.  I'm really struggling with generators

**Comment by dominicbarnes** [comment]
Hmm, I just looked at [unyield](https://github.com/matthewmueller/unyield)'s code, but it doesn't look like this will be an option.

But I think I'll stick to my point that it's not that hard to add `function () {}` to your metalsmith invocation. If you _really_ want to be more clean, just defined a `function noop() {}` somewhere in your file and pass that instead.

**Comment by dominicbarnes** [comment]
If metalsmith eventually uses Promises instead of generators, that will fix this issue too, fwiw.

**Pull request closed without merging**
