### PR TITLE
Fix plugin array test

### LINKED ISSUE #159: Test failure: Uncaught AssertionError: '<p>##two</p>\n' == '<h2 id="two">two</h2>\n'
An update to the way Markdown files are rendered seems to have broken the tests for me on Linux:

Full log:

```text
$ make && make test
make: `node_modules' is up to date.


  Metalsmith
    ✓ should expose a constructor
    ✓ should not require the `new` keyword
    ✓ should error without a working directory
    ✓ should use `./src` as a default source directory
    ✓ should use `./build` as a default destination directory
    ✓ should default clean to `true`
    #use
      ✓ should add a plugin to the plugins stack
    #ignore
      ✓ should add an ignore file to the internal ignores list
    #directory
      ✓ should set a working directory
      ✓ should get the working directory
      ✓ should be able to be absolute
      ✓ should error on non-string
    #source
      ✓ should set a source directory
      ✓ should get the full path to the source directory
      ✓ should be able to be absolute
      ✓ should error on non-string
    #destination
      ✓ should set a destination directory
      ✓ should get the full path to the destination directory
      ✓ should be able to be absolute
      ✓ should error on non-string
    #concurrency
      ✓ should set a max number for concurrency
      ✓ should get the max number for concurrency
      ✓ should be infinitely concurrent by default
    #clean
      ✓ should set the clean option
      ✓ should get the value of the clean option
      ✓ should error on non-boolean
    #frontmatter
      ✓ should set the frontmatter option
      ✓ should get the value of the frontmatter option
      ✓ should error on non-boolean
    #metadata
      ✓ should get metadata
      ✓ should set a clone of metadata
      ✓ should error on non-object
    #path
      ✓ should return a path relative to the working directory
    #read
      ✓ should read from a source directory
      ✓ should read from a provided directory
      ✓ should preserve an existing file mode
      ✓ should expose the stats property in each file metadata
      ✓ should not parse frontmatter if frontmatter is false
      ✓ should still read all when concurrency is set
      ✓ should ignore the files specified in ignores
    #write
      ✓ should write to a destination directory
      ✓ should write to a provided directory
      ✓ should chmod an optional mode from file metadata
      ✓ should still write all when concurrency is set
    #run
      ✓ should apply a plugin
      ✓ should run with a provided plugin
      ✓ should support synchronous plugins
    #build
      ✓ should do a basic copy with no plugins
      ✓ should preserve binary files
      ✓ should apply a plugin
      ✓ should remove an existing destination directory
      ✓ should not remove existing destination directory if clean is false

  CLI
    build
      ✓ should error without a metalsmith.json (336ms)
      ✓ should grab config from metalsmith.json (355ms)
      ✓ should grab config from a config.json (355ms)
      ✓ should require a plugin (361ms)
      1) should require plugins as an array


  56 passing (2s)
  1 failing

  1) CLI build should require plugins as an array:

      Uncaught AssertionError: '<p>##two</p>\n' == '<h2 id="two">two</h2>\n'
      + expected - actual

      -<p>##two</p>
      +<h2 id="two">two</h2>
      
      at Array.forEach (native)
      at test/index.js:551:9
      at ChildProcess.exithandler (child_process.js:742:7)
      at maybeClose (child_process.js:1015:16)
      at Socket.<anonymous> (child_process.js:1183:11)
      at Pipe.close (net.js:485:12)



make: *** [test] Error 1
```

### PR DESCRIPTION
**Pull request by Ajedi32**
Fixes #159

### CODE REVIEW

**Comment by Ajedi32** [comment]
Hold on. I'm waiting to see if Travis also fails the build without any changes.

**Comment by Ajedi32** [comment]
As you can see, Travis agrees that the build is currently failing without this patch: https://travis-ci.org/segmentio/metalsmith/builds/75871368

**Comment by woodyrew** [comment]
Any idea when this will be merged?

**Comment by Ajedi32** [comment]
@woodyrew I have no idea. I haven't heard from any of metalsmith's maintainers since I discovered this project. Looking at the contribution graphs, it seems the most recently active maintainer, @dominicbarnes, is no longer a member of the segmentio organization. The most active maintainer and original creator of the project, @ianstormtaylor, hasn't contributed in a while.

There are still a lot of other members in the segmentio organization, so I'm assuming for now that the project is still maintained. We'll see...

**Comment by dominicbarnes** [comment]
Hmmm, sorry we just haven't had the time to really keep up with Metalsmith lately. I'll go ahead and merge this though.

**Comment by Ajedi32** [comment]
Ah okay. So you _are_ still around. That's good to know.

No problem, I totally understand. I'm pretty busy myself these days.

**Pull request merged**
