### PR TITLE
TypeScript Declaration file and test

### PR DESCRIPTION
**Pull request by brianlagerman**
I've added a TypeScript Declaration file, as well as a typescript version of the tests.

I had originally made a pull request for these to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), but they wanted to drop the test due to the fixtures setup (which I thought was just a shame). Plus, it is better if the declaration just pulls down with the package.

Let me know what you think!

### CODE REVIEW

**Comment by bilby91** [comment]
Any change on getting this merged ?

**Comment by bilby91** [comment]
@brianlagerman A few questions that you might be able to help me with :)

`Callback` error parameter shouldn't be `Error | null` ?

Can't we add the real signature for `Plugin` instead of `...args: any[]` ?

Thanks for the awesome work, I'm using the typings and they are working really good!

**Comment by Ajedi32** [comment]
I do have two concerns with this:

1. What is the purpose of `test/typescript.ts`? It seems to be duplicating our existing tests.
2. As I'm not very familiar with Typescript, I'm not particularly comfortable reviewing or maintaining these definitions

**Comment by bilby91** [comment]
@Ajedi32 I think that the content of test/typescript.ts should only use the API and verify that the code compiles correctly. We don't need to write real tests, we have the js ones. Same way https://github.com/DefinitelyTyped/DefinitelyTyped performs validations on typings. What do you think @brianlagerman ?

Regarding your second concern, I don't have issues with helping here with the maintenance of the Typescript side!

**Comment by brianlagerman** [comment]
@bilby91 The `Plugin`, `Callback`, and `Ignore` types were my biggest headaches getting the definition off the ground, so I'm certainly open to improvements if you see any to be made. I'm relatively sure that the `Error` must be included if a `Callback` is provided (I can't find an instance of it being optional, but correct me if you find one). I also ran into issues with the `Plugin` [signature](https://github.com/segmentio/metalsmith#useplugin) when using some real plugins in practice (although I can't find where those were anymore).

@Ajedi32 The `test/typescript.ts` is most certainly a port of the current tests in typescript. I made those mostly for myself just as an extra check that the definition was functional. Those tests certainly would not need to be maintained. On the other hand, they do work (see [mocha ](https://github.com/segmentio/metalsmith/pull/296/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R16) options) so they could help the maintainers. 

I'm not sure how far along the #207 has proceeded, but I would suspect that typescript might be a better [fit](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html), although that's a whole other story...

**Comment by bilby91** [comment]
@brianlagerman Maybe I expressed myself wrong, the error is required, what I'm suggesting is changing the signature to `Error | null`, not to make it optional. It might happen that you do async work in a plugin and you need to execute the callback without an error. At the moment I have to do `callback(null as any, files, metalsmith)`.

I think we can change it to:

```
declare namespace Metalsmith {
  type Plugin = (...args: ((files: IFileMap, metalsmith: Metalsmith, callback: Callback) => any)[]) => void;
  type Callback = (err: Error | null, files: IFileMap, metalsmith: Metalsmith) => void;
  type Ignore = (path: string, stat: Stats) => void;

  interface IFileMap {
    [index: string]: any
  }
}
```
Also, I think we can remove the tests and just make it the same way as DefinitelyTyped. Let me know what you think!

**Comment by brianlagerman** [comment]
@bilby91 Ahh, now I follow you. That looks like it would work fine.

The tests certainly can be removed, they're not executed by the build anyway. Just keep in mind that DefinitelyTyped at least compiles the typescript tests to check type compatibility on build. Here the test is purely manual (Travis isn't compiling or running the typescript tests), so if we drop it we'll have, well, nothing. No big deal either way in my eyes, as any problems with the definition file shouldn't (and won't) hold up regular development or builds.

**Comment by bilby91** [comment]
@brianlagerman Cool!

Regarding the tests, I think that we need to add a `tsc` call against the "test" file in CI, this way we do it in the same fashion. What do you think ?

**Comment by brianlagerman** [comment]
@bilby91 Well yes, that's what you would need to validate the definition in the build, if that's desired. You would be adding a TypeScript compilation step to the build though, which there isn't now.

I do have another test file that I didn't include which is much more 'DefinitelyTyped' style:
[metalsmith-tests.zip](https://github.com/segmentio/metalsmith/files/1751706/metalsmith-tests.zip)

In the end though, so long as the raw `index.d.ts` file pulls down with the metalsmith package, the benefit is achieved. TypeScript compilation is purely a testing scenario.

**Comment by bilby91** [comment]
@brianlagerman Awesome! That should work! Can you update the typings with my previous suggestions ?

@Ajedi32 Are you okey with adding compilation test during build time in CI ?

**Comment by SamB** [comment]
I guess this explains why there's no `@types/metalsmith` package ...

**Comment by SamB** [comment]
Also, it would be good to test the typings on something like the elevator pitch from <https://metalsmith.io/>.

**Comment by brian-lagerman** [comment]
@SamB I wasn't going to proceed with this since metalsmith is dead, but as the leg work was already done I decided to just post it to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35652), so you can watch that space to see when it gets released. If you don't feel like waiting, you can just drop the contents of this [index.d.zip](https://github.com/segmentio/metalsmith/files/3207142/index.d.zip) file into your `\node_modules\metalsmith\` folder and you should be good to go....

**Comment by brian-lagerman** [comment]
Well that was fast, [@types/metalsmith](https://www.npmjs.com/package/@types/metalsmith) is now available...

**Pull request closed without merging**
