### PR TITLE
Explicitely state minimal node engine

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**

### CODE REVIEW

**Comment by AdrieanKhisbe** [comment]
Many Dependencies are outdated.
I can take to do the upgrade.

**Comment by Ajedi32** [comment]
Note that Node 0.12.x is actually technically supported right now, though it is a pain to get working. See: https://github.com/metalsmith/metalsmith#node-version-requirements

So this change would actually drop support for 0.12.x, which I am actually okay with, but I'd prefer to make that change as part of a major release.

One other alternative to dropping support for 0.12.x is to implement #207,

Anyone else have any thoughts on this?

**Comment by AdrieanKhisbe** [comment]
Babel 6 is cool, and a cool compromise.
I can take care of this if you'd like to.
that will enable us to continue support 0.10.

**Comment by woodyrew** [comment]
I think the Babel option is a bit better for compatibility.

Removing `0.12.x` support isn't the end of the world, people can still use the latest version of Metalsmith `2.x`, as long as the plugin api remains compatible I don't see it as an issue.

**Comment by Ajedi32** [comment]
Yeah, if we can continue to support older Node versions without that interfering too much with future development then we should. Node 0.10 is technically [still supported by Node until October][lts-support], and Node 0.12 is [supported until December][lts-support].

If you want to try to get Babel working, go for it!

[lts-support]: https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png

**Comment by AdrieanKhisbe** [comment]
> If you want to try to get Babel working, go for it!
@Ajedi32, you mean me? or @woodyrew

**Comment by Ajedi32** [comment]
@AdrieanKhisbe I was responding to that bit where you said:

> I can take care of this if you'd like to.

But either of you can work on it if you want to. :wink:

**Comment by AdrieanKhisbe** [comment]
Will do :)

**Comment by AdrieanKhisbe** [comment]
Shall we merge this, or I pursue work on this branch?

**Comment by Ajedi32** [comment]
@AdrieanKhisbe If you change this to only require Node 0.12.x I'll go ahead and merge it, since 0.12.x is actually the current minimum Node version we support.

After Babel is implemented we can probably lower the requirement even further to 0.10.x, and remove those extra instructions on how to run Metalsmith on 0.12.x from the README. (And remove the extra logic for passing flags to Node from the Makefile and from `bin/metalsmith`.)

**Comment by woodyrew** [comment]
You're right, Metalsmith `2.0.x` doesn't support Node `0.10.x` anyway. You have to use Metalsmith `1.7.1`.

I'm good for this too.

**Comment by Zearin** [comment]
It’s now October, so Node 0.10 can go bye-bye!

Just a little longer till we can do the same with Node 0.12. 

:D

**Comment by AdrieanKhisbe** [comment]
Time should have made is effects. 😉

**Comment by Ajedi32** [comment]
Yep, I'm fine with dropping support for Node 0.12 now. This change is still a breaking change though, so if we still want to pursue a 2.4 release we should get that release out _before_ merging this.

Also, if this PR is intended to drop support for 0.12 (and not just clarify the existing Node versions we support, as its title implies) then you should also update the README to remove the sections about Node 0.10 and 0.12.

**Pull request closed without merging**
